a1l: a1p1.c a1p2.c a1p3.c a1p4.c a1p5.c tictactoe.c tictactoe.h
	gcc a1p1.c tictactoe.c -Wall -ansi -pedantic -o a1p1
	gcc a1p2.c tictactoe.c -Wall -ansi -pedantic -o a1p2
	gcc a1p3.c tictactoe.c -Wall -ansi -pedantic -o a1p3
	gcc a1p4.c tictactoe.c -Wall -ansi -pedantic -o a1p4
	gcc a1p5.c tictactoe.c -Wall -ansi -pedantic -o a1p5
